{% set name = "xonda" %}
{% set version = "0.8.0" %}
{% set sha256 = "d02014bfd31968db95041e66931cb0a2210f8297a55478459b254cc25266fe67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gforsyth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - xonsh >=0.8.0
    - conda

test:
  requires:
    - pytest
  source_files:
    - tests/
    - xontrib/
  commands:
    - py.test -v .

about:
  home: https://github.com/gforsyth/xonda
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'This is a thin wrapper around conda for use with xonsh'

  doc_url: https://github.com/gforsyth/xonda
  dev_url: https://github.com/gforsyth/xonda

extra:
  recipe-maintainers:
    - CJ-Wright
    - gforsyth
