travis:
  secure:
    BINSTAR_TOKEN: aR3eGcZw3HuB8c/ysq5mtpuycK3G5mizi2tcPKOA+LsOHfxsyawNy+WeNIOx0TTY8WpdOB6z6kYuO7d1LzyiKTlg515iSEh/IMna294SPbsTYRU4UY4RqAWkgrb5LAEZ/6Y7Fey2NIK+J7Wm3e1BOrjsVrX09opeRwHOADjPIH2db46q/h2ujoD5WVqpoozKH21eEj6B4z82dH6kngPzUmC7Ux8V0qMs4OMyLw13+PS3FAMCD/m1IZkUEN/3+QBx0G0pEj5TzEblOPT8rZBYYtBvgkEkVUPtXwIqi+RV74LDT2JjcB8CjlRCwDyj9Sm3l/K3nF7cXAT1zLOiQuj6BIT6fBLW6zuCEcztAStL8PAxoyy5bJiTaoGMnGW40iZPhAGN0sraPw4mzsjsLtXzVRAub5pzlx6sD3g5yuqMxPl5YOKsR8fZaR4u8Hjtw+UiR++ZvAe14oWY5uwupmtu7cFeomwhgeQbJbv9Mv9UPjYsVISHzA92n5W9Og0D3jRr6OpfELx8+rElWxuDlX2uogfCoz5FGNz2AHy4cRcIepDORPR2lJ15RAApBqewiDdQKt3xwuGHzNuLxEshhrKetabcgH4QCb6e/uQ8eB6u0JDWGfajan2pcfngNvTX5BqlOgXqX5pU94aaz5gP6JYmxG65PQdrHOsPosExu9jlOuk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
