travis:
  secure:
    BINSTAR_TOKEN: G4Aiyl+qS8m3dYIJXVCLZlttLPwP5xR7AgAZ9YeF5ogxlsDef3D3wfJrl7nj+hDRJnYtaLIuHYGC8PlECrKJWBUTG4L1OqIvsBOsok6rS455+pYgdQ5cJGFXJZm1JdTAoFXI/H12JTz9Zp+0UU2XahvXdLM0G0iTkds+rcDXE9oM7jY0yYhdvIrrff57erMtlVoEHLIzKrJn0QXq2eAoTDwHAAm/trR8E1XCCfLVxmXQTp454Z54AldVRS6E/aN2ZtHkzuL5Rl/5J6tZWZfa648yaulDCWaQ/BN7/dEURoezP+mXJidYQbJcecXv8az/TtS37XzCNThrJH5MMe1VHBrKFD+JjiFO5+aLk1NloD21yq6VQ0uDdWsxVkEb2ZW3Xu0BdvSmkxxmK+1W2kIIMFushlMdnWthtjZHli1AS5asCQJoFSvJLw4tj1qlZ54hISwr+y6hasQ09X8BoNwMaSvHvaFBFtenGEQJCLKX3zJDI0LsuIOQK03Ku+XcBQnQz09q6Ikc2oOG3q1WEj0wZAmkC4aP3j3gi817ASf0tNgbocGfX35uzanniyfyV+TeQO9l4LXDG48y3qaLyj/UDV1lr5S8nDkfPl31tb3Mn78Awm9iPgHyUmTshDUYKOgCVfFGWPGtaxq2gSuWj3KqlIIElVhwD//4cR1HVPDDckE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
